/*
 * Copyright (c) 2021, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
 *
 * WSO2 Inc. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service.proto

package org.wso2.carbon.identity.conditional.auth.functions.user.grpc;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface JsonRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:JsonRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string JsonString = 1;</code>
     */
    java.lang.String getJsonString();
    /**
     * <code>string JsonString = 1;</code>
     */
    com.google.protobuf.ByteString
        getJsonStringBytes();
  }
  /**
   * Protobuf type {@code JsonRequest}
   */
  public  static final class JsonRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:JsonRequest)
      JsonRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use JsonRequest.newBuilder() to construct.
    private JsonRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private JsonRequest() {
      jsonString_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private JsonRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              jsonString_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.internal_static_JsonRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.internal_static_JsonRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest.class, org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest.Builder.class);
    }

    public static final int JSONSTRING_FIELD_NUMBER = 1;
    private volatile java.lang.Object jsonString_;
    /**
     * <code>string JsonString = 1;</code>
     */
    public java.lang.String getJsonString() {
      java.lang.Object ref = jsonString_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jsonString_ = s;
        return s;
      }
    }
    /**
     * <code>string JsonString = 1;</code>
     */
    public com.google.protobuf.ByteString
        getJsonStringBytes() {
      java.lang.Object ref = jsonString_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jsonString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getJsonStringBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, jsonString_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getJsonStringBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, jsonString_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest)) {
        return super.equals(obj);
      }
      org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest other = (org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest) obj;

      boolean result = true;
      result = result && getJsonString()
          .equals(other.getJsonString());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + JSONSTRING_FIELD_NUMBER;
      hash = (53 * hash) + getJsonString().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code JsonRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:JsonRequest)
        org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.internal_static_JsonRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.internal_static_JsonRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest.class, org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest.Builder.class);
      }

      // Construct using org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        jsonString_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.internal_static_JsonRequest_descriptor;
      }

      @java.lang.Override
      public org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest getDefaultInstanceForType() {
        return org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest build() {
        org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest buildPartial() {
        org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest result = new org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest(this);
        result.jsonString_ = jsonString_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest) {
          return mergeFrom((org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest other) {
        if (other == org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest.getDefaultInstance()) return this;
        if (!other.getJsonString().isEmpty()) {
          jsonString_ = other.jsonString_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object jsonString_ = "";
      /**
       * <code>string JsonString = 1;</code>
       */
      public java.lang.String getJsonString() {
        java.lang.Object ref = jsonString_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          jsonString_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string JsonString = 1;</code>
       */
      public com.google.protobuf.ByteString
          getJsonStringBytes() {
        java.lang.Object ref = jsonString_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jsonString_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string JsonString = 1;</code>
       */
      public Builder setJsonString(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        jsonString_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string JsonString = 1;</code>
       */
      public Builder clearJsonString() {
        
        jsonString_ = getDefaultInstance().getJsonString();
        onChanged();
        return this;
      }
      /**
       * <code>string JsonString = 1;</code>
       */
      public Builder setJsonStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        jsonString_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:JsonRequest)
    }

    // @@protoc_insertion_point(class_scope:JsonRequest)
    private static final org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest();
    }

    public static org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<JsonRequest>
        PARSER = new com.google.protobuf.AbstractParser<JsonRequest>() {
      @java.lang.Override
      public JsonRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JsonRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<JsonRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JsonRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface JsonResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:JsonResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string JsonString = 1;</code>
     */
    java.lang.String getJsonString();
    /**
     * <code>string JsonString = 1;</code>
     */
    com.google.protobuf.ByteString
        getJsonStringBytes();
  }
  /**
   * Protobuf type {@code JsonResponse}
   */
  public  static final class JsonResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:JsonResponse)
      JsonResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use JsonResponse.newBuilder() to construct.
    private JsonResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private JsonResponse() {
      jsonString_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private JsonResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              jsonString_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.internal_static_JsonResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.internal_static_JsonResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse.class, org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse.Builder.class);
    }

    public static final int JSONSTRING_FIELD_NUMBER = 1;
    private volatile java.lang.Object jsonString_;
    /**
     * <code>string JsonString = 1;</code>
     */
    public java.lang.String getJsonString() {
      java.lang.Object ref = jsonString_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jsonString_ = s;
        return s;
      }
    }
    /**
     * <code>string JsonString = 1;</code>
     */
    public com.google.protobuf.ByteString
        getJsonStringBytes() {
      java.lang.Object ref = jsonString_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jsonString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getJsonStringBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, jsonString_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getJsonStringBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, jsonString_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse)) {
        return super.equals(obj);
      }
      org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse other = (org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse) obj;

      boolean result = true;
      result = result && getJsonString()
          .equals(other.getJsonString());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + JSONSTRING_FIELD_NUMBER;
      hash = (53 * hash) + getJsonString().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code JsonResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:JsonResponse)
        org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.internal_static_JsonResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.internal_static_JsonResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse.class, org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse.Builder.class);
      }

      // Construct using org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        jsonString_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.internal_static_JsonResponse_descriptor;
      }

      @java.lang.Override
      public org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse getDefaultInstanceForType() {
        return org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse.getDefaultInstance();
      }

      @java.lang.Override
      public org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse build() {
        org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse buildPartial() {
        org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse result = new org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse(this);
        result.jsonString_ = jsonString_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse) {
          return mergeFrom((org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse other) {
        if (other == org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse.getDefaultInstance()) return this;
        if (!other.getJsonString().isEmpty()) {
          jsonString_ = other.jsonString_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object jsonString_ = "";
      /**
       * <code>string JsonString = 1;</code>
       */
      public java.lang.String getJsonString() {
        java.lang.Object ref = jsonString_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          jsonString_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string JsonString = 1;</code>
       */
      public com.google.protobuf.ByteString
          getJsonStringBytes() {
        java.lang.Object ref = jsonString_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jsonString_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string JsonString = 1;</code>
       */
      public Builder setJsonString(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        jsonString_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string JsonString = 1;</code>
       */
      public Builder clearJsonString() {
        
        jsonString_ = getDefaultInstance().getJsonString();
        onChanged();
        return this;
      }
      /**
       * <code>string JsonString = 1;</code>
       */
      public Builder setJsonStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        jsonString_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:JsonResponse)
    }

    // @@protoc_insertion_point(class_scope:JsonResponse)
    private static final org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse();
    }

    public static org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<JsonResponse>
        PARSER = new com.google.protobuf.AbstractParser<JsonResponse>() {
      @java.lang.Override
      public JsonResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JsonResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<JsonResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JsonResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.wso2.carbon.identity.conditional.auth.functions.user.grpc.Service.JsonResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JsonRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JsonRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JsonResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JsonResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rService.proto\"!\n\013JsonRequest\022\022\n\nJsonSt" +
      "ring\030\001 \001(\t\"\"\n\014JsonResponse\022\022\n\nJsonString" +
      "\030\001 \001(\t2:\n\013grpcService\022+\n\ngrpcInvoke\022\014.Js" +
      "onRequest\032\r.JsonResponse\"\000B?\n=org.wso2.c" +
      "arbon.identity.conditional.auth.function" +
      "s.user.grpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_JsonRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_JsonRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JsonRequest_descriptor,
        new java.lang.String[] { "JsonString", });
    internal_static_JsonResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_JsonResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JsonResponse_descriptor,
        new java.lang.String[] { "JsonString", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
